### ISSUE TITLE
Error code: File not found

### ISSUE THREAD

**Issue by Duri-cell** [kents00/Kwobbler#1]
Hey! I have this error code popping and out it says:

File not found: C:\Users\Pc\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Kwobbler-main\..\Kwobbler/data\Kwobbler.blend

For some reason Blender can not find this file even tho that file is there.
Please help. I cannot continue withouth it.

**Comment by kents00** [comment]
Hello, I update the folder location and just to make sure if you install the add-on filename would be `Kwobbler-main`
